services:
  - type: web
    name: siryan-api
    runtime: go
    plan: free
    buildCommand: go build -o bin/api ./cmd/api
    startCommand: ./bin/api
    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: 10000