use_default_settings: true
general:
  instance_name: "siryan-searx"
  enable_metrics: false
server:
  secret_key: "siryan-change-this-to-long-random-string-please"
  limiter: false
  image_proxy: false
  method: "GET"
search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
  formats:
    - html
    - json
outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0